### ISSUE TITLE
how to open ontol-docs/dna-ontology-tree.html in Google browser?

### ISSUE THREAD

**Issue by ashkotin** [ontoinsights/deep_narrative_analysis#10]
I can't get it rendering. When I downloaded the html, the page is empty:
![image](https://github.com/ontoinsights/deep_narrative_analysis/assets/2370257/14c74583-9cf7-44c9-ab32-e096684ec276)

**Comment by AndreaWesterinen** [comment]
I just performed a download and tried it in Safari, Firefox and Chrome. They all worked. 

What browser caused a problem? Can you try it again?

Also, the page is available online at https://ontoinsights.github.io/dna-ontologies/

**Comment by ashkotin** [comment]
I have Google Chrome 118.0.5993.11, 64-bit. And if https://ontoinsights.github.io/dna-ontologies/is the same it's fine as the latter works.

**Comment by ashkotin** [comment]
Now it works!
